# Generated by Django 3.0.7 on 2020-08-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='content',
            field=models.TextField(max_length=9999, null=True),
        ),
    ]
